// Code generated by "gqlgenmarshal -type=Jimbob"; DO NOT EDIT.

package carl

import (
	"encoding/json"
	"fmt"
	"io"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kazerp-0]
	_ = x[Blargh-1]
	_ = x[Ugh-2]
}

func (i Jimbob) MarshalGQL(w io.Writer) {
	if err := json.NewEncoder(w).Encode(i); err != nil {
		panic(fmt.Errorf("error marshaling Jimbob"))
	}
}

func (i *Jimbob) UnmarshalGQL(v interface{}) error {
	check, ok := v.(int)
	if !ok {
		return fmt.Errorf("Jimbob must be a valid int value")
	}

	switch Jimbob(check) {
	case Kazerp:
		*i = Kazerp
	case Blargh:
		*i = Blargh
	case Ugh:
		*i = Ugh
	default:
		return fmt.Errorf("unknown Jimbob value %[1]s", check)
	}

	return nil
}
